language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "beanstalk-sdc-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

# before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: beanstalk-sdc # see README
  api_key:
    secure: 6d87b20e-0946-4d73-b4b8-ded2ae94978b # see README

#     $ heroku authorizations:create
# Creating OAuth Authorization... done
# Client:      <none>
# ID:          91cfbce9-796b-41a9-ae0e-3687a63d6771
# Description: Long-lived user authorization
# Scope:       global
# Token:       6d87b20e-0946-4d73-b4b8-ded2ae94978b
# Updated at:  Sat Dec 21 2019 14:46:38 GMT-0500 (Eastern Standard Time) (less than a minute ago)
